sqlite3:
  :adapter: sqlite3
  :database: spec/db/acts_as_struct_test.sqlite3.db

# postgresql:
#   :adapter: postgresql
#   :username: rails
#   :password: rails
#   :database: acts_as_struct_test
#   :min_messages: ERROR
# 
# mysql:
#   :adapter: mysql
#   :host: localhost
#   :username: rails
#   :password: rails
#   :database: acts_as_struct_test
